name: Release
on:
  workflow_dispatch:
  push:
    branches: [main, alpha, beta, next]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: SocialGouv/actions/autodevops-release@v1
      with:
        github-token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        author-name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        author-email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}

# name: Release

# on:
#   workflow_dispatch:
#   push:
#     branches: [main, alpha, beta, next]

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#           ssh-key: ${{ secrets.DEPLOY_KEY }}

#       - name: Semantic Release
#         uses: cycjimmy/semantic-release-action@v2
#         with:
#           semantic_version: 17
#           extra_plugins: |
#             @semantic-release/changelog@5.0.1
#             @semantic-release/git@9.0.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
